name: Pacman generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # run every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Guru-1205
        env:
          OUTPUT_FILE: dist/pacman-contribution-graph.svg

      - name: Prepare dark mode duplicate
        run: |
          if [ -f dist/pacman-contribution-graph.svg ]; then
            cp dist/pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg
          else
            echo "❌ dist/pacman-contribution-graph.svg not found!"
            exit 1
          fi

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
