name: Pacman generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pacman-contribution-graph CLI
        run: npm install -g pacman-contribution-graph

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate pacman SVG
        run: |
          pacman-contribution-graph Guru-1205 > dist/pacman-contribution-graph.svg

      - name: Create dark-mode copy
        run: cp dist/pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
